/**
 * Bundles every .txt and .json file under lib/study/prompts/ into a single
 * TypeScript module so the serverless function can import them as regular
 * JS modules (no runtime readFileSync, no file-tracing required).
 *
 * Runs automatically from the `build` and `dev` scripts in package.json.
 * If you edit a .txt file, re-run `pnpm gen:prompts` (or restart dev).
 */

import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const PROMPTS_DIR = join(process.cwd(), "lib", "study", "prompts");
const OUT_FILE = join(PROMPTS_DIR, "generated.ts");

function toTemplateLiteral(raw: string): string {
  // Escape backticks, backslashes, and `${` so the text survives as a
  // template literal regardless of content.
  return raw
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

function main() {
  const files = readdirSync(PROMPTS_DIR)
    .filter((f) => f.endsWith(".txt") || f.endsWith(".json"))
    .sort();

  const txtEntries: string[] = [];
  const jsonEntries: string[] = [];

  for (const file of files) {
    const contents = readFileSync(join(PROMPTS_DIR, file), "utf-8");

    if (file.endsWith(".txt")) {
      txtEntries.push(`  ${JSON.stringify(file)}: \`${toTemplateLiteral(contents.trim())}\``);
    } else {
      // Validate JSON at build time; emit as a literal for type inference.
      JSON.parse(contents);
      jsonEntries.push(`  ${JSON.stringify(file)}: ${contents.trim()}`);
    }
  }

  const body = `// AUTO-GENERATED by scripts/generate-prompts.ts. Do not edit by hand.
// Regenerate with: pnpm gen:prompts

export const TEXT_FILES: Record<string, string> = {
${txtEntries.join(",\n")}
};

export const JSON_FILES: Record<string, unknown> = {
${jsonEntries.join(",\n")}
};
`;

  writeFileSync(OUT_FILE, body, "utf-8");
  console.log(
    `Generated ${OUT_FILE} (${txtEntries.length} .txt, ${jsonEntries.length} .json)`,
  );
}

main();
